version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      # Checkout source code
      - checkout

      # Restore cache
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific Gemfile.lock checksum
            # when this file is changed, this key will fail
            - cache-build-{{ checksum "Gemfile.lock" }}
            # Fallback cache
            - cache-build
            
      # Bundle install dependencies
      - run:
          name: bundle-install
          command: 'bundle install --path vendor/bundle'
      
      # Build
      - run:
          name: jekyll-build
          command: 'bundle exec jekyll build'
      
      # Save cache
      - save_cache:
          # Gemfile.lock cache
          key: cache-build-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          # Fallback cache
          key: cache-build
          paths:
            - vendor/bundle
